version: '3.8'
services:
  web:
    image: node
    command: npm start
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
    restart: always
    tty: true
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: